name: Sync
on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  sync:
    name: Sync to Private Fork
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kong source code
      uses: actions/checkout@v3
    - name: Checkout Kong EE source code
      uses: actions/checkout@v3
      with:
        repository: Kong/colin-kong-ee
        path: kong-ee
        ref: master
        token: ${{ secrets.PAT }}
    - name: Setup github config
      run: |
        git config --global user.email "team-eng-enablement+github-bot@konghq.com"
        git config --global user.name "Eng Enablement"
    - name: Setup Kong CE as a remote on Kong EE
      run: |
        pushd kong-ee
        git remote add kong-ce https://github.com/Kong/colin-kong
        git fetch kong-ce
    - name: Setup the sync branch
      run: |
        pushd kong-ee
        git checkout kong-ce $GITHUB_HEAD_REF
        git checkout -b sync/$GITHUB_HEAD_REF
        git push -u origin sync/$GITHUB_HEAD_REF
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
