name: Sync
on:
  push:
    branches:
    - master

jobs:
  sync:
    name: Sync to Private Fork
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kong source code
      uses: actions/checkout@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
